name: Nested reusable workflow for AdHoc Staging Deployment that acts as a wrapper around helper workflows

on:
  workflow_call:
    inputs:
      file: 
        description: "Dotenv file to use"
        required: true
        type: string
    secrets:
      github-pat:
        description: "GitHub PAT"
        required: true
      slack-bot-token: 
        description: "Slack Bot Token"
        required: true

permissions:
  contents: read
  id-token: write
  pull-requests: write
  deployments: write

jobs:
  fetch_sha:
    name: Fetch SHA of most recent commit on current branch
    uses: rdadlani/cicd-poc-shared-workflows/.github/workflows/helper_fetch_sha.yml@main
  
  load_dotenv:
    uses: rdadlani/cicd-poc-shared-workflows/.github/workflows/helper_load_dotenv.yml@main
    with:
      file: ${{ inuputs.file }}
  
  create_deployment:
    name: Create github deployment
    needs: [fetch_sha, load_dotenv]
    uses: rdadlani/cicd-poc-shared-workflows/.github/workflows/helper_create_github_deployment.yml@main
    with:
      aws-environment: ${{ needs.load_dotenv.outputs.aws_environment }}
      git-sha: ${{ needs.fetch_sha.outputs.git-sha }}
    secrets:
      github-pat: ${{ secrets.github-pat }}

  build:
    needs: [fetch_sha, load_dotenv]
    uses: rdadlani/cicd-poc-shared-workflows/.github/workflows/helper_build_push_ecr.yml@main
    with:
      git-sha: ${{ needs.fetch_sha.outputs.git-sha }}
      role-to-assume: ${{ needs.load_dotenv.outputs.role_to_assume }}

  deploy:
    needs: [build, load_dotenv]
    uses: rdadlani/cicd-poc-shared-workflows/.github/workflows/helper_deploy_to_ecs.yml@main
    with: 
      image: ${{ needs.build.outputs.image }}
      ecs-service: ${{ needs.load_dotenv.outputs.ecs_service }}
      ecs-service-two: ${{ needs.load_dotenv.outputs.ecs_service2 }} #optional
      # Note: the only difference between staging and production as far as the reusable 
      #       workflows are concerned is the role to assume - all other steps infer the account based on the role
      role-to-assume: ${{ needs.load_dotenv.outputs.role_to_assume }}
      aws-environment: ${{ needs.load_dotenv.outputs.aws_environment }}
    secrets: 
      github-pat: ${{ secrets.github-pat }}
  
  update_deployment:
    name: Update github deployment
    needs: [fetch_sha, load_dotenv, create_deployment, deploy]
    uses: rdadlani/cicd-poc-shared-workflows/.github/workflows/helper_update_github_deployment.yml@main
    with:
      aws-environment: ${{ needs.load_dotenv.outputs.aws_environment }}
      deployment-id: ${{ needs.create_deployment.outputs.deployment_id }}
    secrets:
      github-pat: ${{ secrets.github-pat }}  
  
  slack_notifyer:
    needs: deploy
    uses: rdadlani/cicd-poc-shared-workflows/.github/workflows/helper_notify_slack.yml@main
    secrets:
      slack-bot-token: ${{ secrets.slack-bot-token }}
#TODO: make output variable names consistent. lots of - vs _ driving me crazy
#TODO: make file naming scheme consistent. right now we have some with - and others with _ and it's driving me crazy
  pull_request_notifyer:
    needs: [deploy, fetch_sha]
    uses: rdadlani/cicd-poc-shared-workflows/.github/workflows/helper_pull_request_notifyer.yml@main
    with: 
      git-sha: ${{ needs.fetch_sha.outputs.git-sha }}
