name: Reusable workflow to update a GitHub deployment

on:
  workflow_call:
    inputs:
      aws-environment: 
        description: "Name of the environment"
        required: true
        type: string
      deployment-id:
        description: "The ID of the Github Environments deployment"
        required: true
        type: string
    secrets:
      github-pat:
        description: "GitHub PAT"
        required: true

permissions:
  deployments: write

jobs:
  update_deployment:
    name: Update github deployment

    runs-on: ubuntu-latest

    steps:
      - name: Update deployment status - success
        uses: chrnorm/deployment-status@v2
        if: success()
        with:
          token: ${{ secrets.github-pat }}
          environment: ${{ inputs.aws-environment }}
          deployment-id: ${{ inputs.deployment-id }}
          state: 'success'
      - name: Update deployment status - failure
        uses: chrnorm/deployment-status@v2
        if: failure()
        with:
          token: ${{ secrets.github-pat }}
          environment: ${{ inputs.aws-environment }}
          deployment-id: ${{ inputs.deployment-id }}
          state: 'failure'
