name: Reusable workflow to read .env 
on: 
  workflow_call:
    inputs:
      file: 
        description: "dotenv file to be used"
        required: true 
        type: string

jobs:
  load_dotenv:
    name: Load Dotenv
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Dotenv Action
      run: |
        while read line; do
          echo "$line" >> $GITHUB_ENV
        done < ${{ inputs.file }}


