name: Reusable workflow to read .env 
on: 
  workflow_call:
    inputs:
      file: 
        description: "dotenv file to be used"
        required: true 
        type: string
  
    outputs:
      job_outputs:
        value: ${{ jobs.load_dotenv.outputs.step_outputs }}


jobs:
  load_dotenv:
    name: Load Dotenv
    runs-on: ubuntu-latest

    outputs:
      step_outputs: ${{ steps.dotenv.outputs.result }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Dotenv Action
      id: dotenv
      uses: falti/dotenv-action@v0.2.8
      with:
        path: ${{ inputs.file }}
        log-variables: true

