name: Reusable workflow to deploy image to ECS

on:
  workflow_call:
    inputs:
      aws-environment: 
        description: "Name of the environment"
        required: true
        type: string
      deployment-id:
        description: "The ID of the Github Environments deployment"
      state: 
        description: "The state of the deployment to ECS"
        require: true
        type: string
    secrets:
      github-pat:
        description: "GitHub PAT"
        required: true

permissions:
  deployments: write

jobs:
  update_deployment:
    name: Update github deployment

    runs-on: ubuntu-latest

    steps:
      - name: Update deployment status
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.github-pat }}
          environment: ${{ inputs.aws-environment }}
          deployment-id: ${{ inputs.deployment-id }}
          state: ${{ inputs.state }}
